name: "Lab 07 - Artifacts"
on: { workflow_dispatch {} }
jobs:
  build-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Create build-info.txt
        run: |
          echo "Repo: $GITHUB_REPOSITORY" > build-info.txt
          echo "SHA: $GITHUB_SHA" >> build-info.txt
          echo "Run ID: $GITHUB_RUN_ID" >> build-info.txt


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info.txt