name: "Lab 09 - Permissions"
on: { workflow_dispatch: {} }
permissions:
  contents: read
jobs:
  print-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print SHA
        run: |
          echo SHA: ${GITHUB_SHA}
